exp_name: "exp_tmp"

model_name: resnet18
batch_size: 128
base_epochs: 100  # 修正: 0だと学習が進まないため適切な値に変更
base_ndata: 10000

dataset:
  train_ds_str: "cifar100_train"
  val_ds_str: "cifar100_val"


wd: ???
div: ???
ndata: ???
optim_lr: ???

hydra:
  mode: MULTIRUN
  
  # Joblibランチャー設定 (並列実行用)
  launcher:
    n_jobs: 6          # 並列プロセス数（=使用するGPU数)
    batch_size: 1      # "auto" ではなく 1 を明示的に指定

  sweeper:
    params:
      wd: 0, 1e-4, 1e-3
      div: 1, 4
      ndata: 10000
      optim_lr: 
        [{optim: sgd, lr: 0.1}, {optim: adamw, lr: 0.005}]

  run:
    dir: ./${exp_name}/runs/run_${now:%Y-%m-%d_%H-%M-%S_%f}
  sweep:
    dir: ./${exp_name}/runs/multirun/run_${now:%Y-%m-%d_%H-%M-%S_%f}
    subdir: ${hydra.job.num}

